### ISSUE TITLE
 The module's source code could not be parsed (Deno in VS Code)

### ISSUE THREAD

**Issue by ClariNerd617** [netbymatt/nexrad-level-2-data#2]
Full text of error: The module's source code could not be parsed: Expected ';', '}' or <eof> at https://github.com/netbymatt/nexrad-level-2-data/blob/main/src/index.js:7:11

Attempting to pull Level2 Nexrad data from S3 and work with it in TypeScript, using Deno to avoid the `node_modules` nightmare.

**Comment by netbymatt** [comment]
The URL that you're using returns an html page not a javascript file. Please see this discussion https://github.com/denoland/deno/issues/5543

Also, I'm not planning to support Deno.
